Docker Container Work
torrust/torrust-index pull request #248
Opened 2023-08-03 15:20 UTC by da2ce7

2023-08-04 11:04 UTC, josecelano requested changes

2023-08-04 11:04 UTC, josecelano commented on .github/workflows/container.yml
> +        run: docker image inspect index-backend:local
Hi @da2ce7 when you generate the local docker image here, is that image available when you run:

```
- id: test
  name: Run Integration Tests
  run: ./docker/bin/run-e2e-tests.sh
```

here: https://github.com/torrust/torrust-index-backend/pull/248/files#diff-cf3dd985ec02b2c727885d15dd9a5eca1e2f1ed708cb81406d99f57099aed253R126

I see it's not: https://github.com/torrust/torrust-index-backend/actions/runs/5754190543/job/15598977722?pr=248#step:3:251

You need to save an artefact or push it to a registry.

2023-08-04 11:04 UTC, josecelano commented on .github/workflows/container.yml
> +name: Container
Hi @da2ce7, I would change the name to something like:

`Generate local docker image`

Or any other alternative, but I think `Container` is too generic.

Why do you create an independent workflow if the putout (the local docker image) is only used in the testing workflow?

I think you can simply move these steps to the `integration` job in the `testing` workflow for now.

2023-08-25 17:31 UTC, da2ce7 commented on compose.yaml
> +    image: index-backend:local
This is not a problem. You can run `docker build --tag index-backend:local .` and it will be included in your local cache.

2023-10-14 22:11 UTC, da2ce7 commented
closed in preference for:
 - #338

2023-10-14 22:11 UTC, closed without merging